image: registry.gitlab.com/bluestarsports/devops/docker-base-images/bss-php71:latest

before_script:
  - set -xe
  - apt-get update -y
  - apt-get install -y php7.0
  - apt-get install -y php7.0-xml


after_script:
  - killall php

stages:
  - setup
  - test
  - build

setup:
  type: setup
  script:
    - composer install --quiet --no-interaction
    - cp .env.testing .env
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - vendor/
  artifacts:
    expire_in: 1 week
    paths:
      - vendor/

test:
  services:
    - postgres:9.6-alpine
  variables:
    POSTGRES_USER: root
    POSTGRES_PASSWORD: root
    POSTGRES_DB: npdb-usafb
  type: test
  script:
    - mv .env.testing .env
    - php artisan migrate:refresh --seed
    - composer test

lint:
  type: test
  script:
    - composer lint

automation:
  services:
    - postgres:9.6-alpine
  variables:
    POSTGRES_USER: root
    POSTGRES_PASSWORD: root
    POSTGRES_DB: npdb-usafb
  type: test
  script:
    - mv .env.testing .env
    - composer env:prereq
    - php artisan migrate:refresh --seed
    - php -S localhost:8000 -t public 1>/dev/null &
    - composer --global config process-timeout 20000
    - composer test:reg


build:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
    DOCKER_HOST: tcp://localhost:2375
  services:
    - docker:dind
  before_script:
    - docker info
  stage: build
  only:
  #  - develop
    - kubernetes-npdb-usafb-build
  when: manual
  script:
    - docker login registry.gitlab.com -u npdbtest -p $gitlab_personal_token
    - docker build -t registry.gitlab.com/bluestarsports/npdb-usafb-api .
    - docker push registry.gitlab.com/bluestarsports/npdb-usafb-api

