image: edbizarro/gitlab-ci-pipeline-php:7.1-alpine

before_script:
  - set -xe
  - apk add --update php7-simplexml

after_script:
  - killall php

stages:
  - setup
  - test

setup:
  type: setup
  script:
    - composer install --quiet --no-interaction
    - cp .env.testing .env
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - vendor/
  artifacts:
    expire_in: 1 week
    paths:
      - vendor/
      - .env

test:
  services:
    - postgres:9.6-alpine
  variables:
    POSTGRES_USER: root
    POSTGRES_PASSWORD: root
    POSTGRES_DB: npdb-usafb
  type: test
  script:
    - php artisan migrate:refresh --seed
    - composer test

lint:
  type: test
  script:
    - composer lint

automation:
  services:
    - postgres:9.6-alpine
  variables:
    POSTGRES_USER: root
    POSTGRES_PASSWORD: root
    POSTGRES_DB: npdb-usafb
  type: test
  script:
    - php artisan migrate:refresh --seed
    - composer env:prereq
    - php -S localhost:8000 -t public 1>/dev/null &
    - composer test:reg

