version: "3.1"
services:
    mailhog:
      image: mailhog/mailhog:latest
      container_name: ussf-mailhog
      ports:
        - "8081:8025"

    redis:
      image: redis:alpine
      container_name: ussf-redis

    postgres:
      image: postgres:9.6-alpine
      container_name: ussf-postgres
      working_dir: /application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=npdb-ussf

    elasticsearch:
      image: elasticsearch:5.3-alpine
      container_name: ussf-elasticsearch

    nginx:
      image: nginx:alpine
      container_name: ussf-nginx
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
      links:
       - php-fpm

    php-fpm:
      build:
        context: .
        dockerfile: docker/php-fpm/Dockerfile
      container_name: ussf-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

      links:
        - mailhog
        - postgres
        - redis
        - elasticsearch
