version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: usafb-redis
      ports:
       - "6379:6379"

    mongo:
      image: mongo:3.0.15-wheezy
      container_name: usafb-mongo
      ports:
       - "27017:27017"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/db:/data/db
      command: mongod --noauth --smallfiles --dbpath /data/db --logpath=/dev/null # --quiet
        
    nginx:
      image: registry.gitlab.com/bluestarsports/devops/docker-base-images/bss-nginx:latest
      container_name: usafb-nginx
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/sites-available/default
      ports:
       - "8000:80"
       - "443"
      links:
       - php-fpm
       - mongo

    php-fpm:
      image: registry.gitlab.com/bluestarsports/npdb-ussf-api/php-fpm:latest
      container_name: usafb-php-fpm
      working_dir: /application
      ports:
       - "9000:9000"
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
      entrypoint: /application/start_application.sh
      links:
       - mongo
       - redis