apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: npdb-usafb-api
  namespace: staging
  labels:
    app: npdb-usafb-api
    track: stable
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: npdb-usafb-api
        track: stable
    spec:
      containers:
      - name: npdb-usafb-app
        image:
          registry.gitlab.com/bluestarsports/npdb-usafb-api:$image_tag
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: npdb-usafb-secrets
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /tempfs
          name: npdb-usafb-efs
      - name: npdb-usafb-nginx
        image:
          registry.gitlab.com/bluestarsports/npdb-usafb-api/npdb-usafb-api-nginx:$image_tag
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: npdb-usafb-secrets
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /tempfs
          name: npdb-usafb-efs
      imagePullSecrets:
      - name: mikeregsecret
      volumes:
      - name: npdb-usafb-efs
        persistentVolumeClaim:
          claimName: npdb-usafb-efs

