<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePlayerTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('player', function (Blueprint $table) {
            $table->increments('id');
            $table->string('usadfb_id', 32); //generated by me
            $table->string('salesforce_id', 32);
            $table->string('first_name', 32);
            $table->string('middle_name', 64);
            $table->string('last_name', 32);
            $table->string('email', 254);
            $table->string('gender', 6);
            $table->string('city', 128);
            $table->string('country', 128);
            $table->string('zip_code', 10);
            $table->dateTime('birth_date');
            $table->string('phone', 30);
            $table->integer('sport_years');
            $table->integer('graduation_year');
            $table->string('grade');
            $table->string('height');
            $table->string('weight');
            $table->boolean('usafb_market');
            $table->text('sports');
            $table->text('positions');
            $table->dateTime('player_last_updated');
            $table->string('address_first_line', 128);
            
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('player');
    }
}
