apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: npdb-usafb-api
  namespace: staging
  labels:
    app: npdb-usafb-api
    track: stable
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: npdb-usafb-api
        track: stable
    spec:
      containers:
      - name: npdb-usafb-api
        image:
          registry.gitlab.com/bluestarsports/npdb-usafb-api
        imagePullPolicy: Always
        env:
        - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
          value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
        envFrom:
          - secretRef:
              name: npdb-usafb-secrets
        ports:
        - containerPort: 9000
      - name: bsp-nginx
        image:
          registry.gitlab.com/bluestarsports/devops/docker-base-images/bss-nginx:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: npdb-usafb-secrets
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: mikeregsecret

